USE [master]
GO

/****** Object:  Database [shop]    Script Date: 05.02.2024 18:08:34 ******/
CREATE DATABASE [shop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'shop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\shop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'shop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\shop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [shop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [shop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [shop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [shop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [shop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [shop] SET ARITHABORT OFF 
GO

ALTER DATABASE [shop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [shop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [shop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [shop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [shop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [shop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [shop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [shop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [shop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [shop] SET  ENABLE_BROKER 
GO

ALTER DATABASE [shop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [shop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [shop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [shop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [shop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [shop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [shop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [shop] SET RECOVERY FULL 
GO

ALTER DATABASE [shop] SET  MULTI_USER 
GO

ALTER DATABASE [shop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [shop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [shop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [shop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [shop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [shop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [shop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [shop] SET  READ_WRITE 
GO

